extends SceneTree
const Comms=preload("res://scripts/crew_comms.gd")
func _init() -> void: call_deferred("run")
func run() -> void:
	DirAccess.make_dir_recursive_absolute("res://output/comms-archive")
	var path: String="res://output/comms-archive/test-%d.json"%OS.get_process_id()
	var first=Comms.new(); first.archive_path=path; root.add_child(first); first.set_process(false)
	first.transmit("brine","A message worth keeping."); first.show_next()
	first.transmit("bill","The gauge is steady."); first.show_next()
	assert(FileAccess.file_exists(path))
	var restored=Comms.new(); restored.archive_path=path; root.add_child(restored); restored.set_process(false)
	assert(restored.history.size()==2 and restored.history[0].speaker=="brine")
	restored.replay_history(1); assert(restored.current.text=="A message worth keeping.")
	assert(restored.history.size()==2)
	for i in range(35): restored.transmit("brine","Record %d"%i); restored.show_next()
	assert(restored.history.size()==30)
	var file:=FileAccess.open(path,FileAccess.WRITE); file.store_string("damaged archive"); file.close()
	var broken=Comms.new(); broken.archive_path=path; root.add_child(broken); broken.set_process(false)
	broken.transmit("bill","Keep the original."); broken.show_next()
	assert(FileAccess.get_file_as_string(path)=="damaged archive","Malformed history preserved")
	print("COMMS ARCHIVE PASS: disk reload, replay, atomic replacement, bounded history, malformed preservation")
	quit()
