"""Read-only checks that generated export fixtures preserve source assertions."""
import hashlib
import json
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'tests/runtime_generated'


class ExportBridgeTests(unittest.TestCase):
    def test_airlock_assertion_body_unchanged(self):
        source = (ROOT / 'tests/test_airlock.gd').read_text(encoding='utf-8')
        expected = source.replace('extends SceneTree', 'extends Node\n# Generated by tools/build_room_export_fixture.py; edit the source fixture.\n@onready var root = get_tree().root\nfunc quit(code: int = 0) -> void: get_tree().quit(code)', 1)
        expected = expected.replace('await process_frame', 'await get_tree().process_frame')
        expected = expected.replace('current_scene=game', 'get_tree().current_scene=game')
        self.assertEqual((OUT / 'airlock.gd').read_text(encoding='utf-8'), expected)
        dispatch = (OUT / 'dispatch.gd').read_text(encoding='utf-8')
        self.assertEqual(dispatch.count('"airlock": preload("res://tests/runtime_generated/airlock.gd")'), 1)

    def test_station_assertion_body_unchanged(self):
        source = (ROOT / 'tests/playtest_production_ten_station.gd').read_text(encoding='utf-8')
        expected = source.replace('extends "res://tests/playtest_nursery_art.gd"',
                                  'extends "res://tests/runtime_generated/room_base.gd"', 1)
        # SceneTree owns process_frame; the exported Node must access its tree.
        # Permit this same context adaptation as the generator, not assertion edits.
        expected = expected.replace('await process_frame', 'await get_tree().process_frame')
        self.assertEqual((OUT / 'station.gd').read_text(encoding='utf-8'), expected)

    def test_recorded_sources_are_current(self):
        records = json.loads((OUT / 'sources.json').read_text())
        self.assertEqual(len(records), 21)
        self.assertIn(Path('tests/drone_dock_checks.gd'), {Path(source) for source in records})
        for source, digest in records.items():
            self.assertEqual(hashlib.sha256((ROOT / source).read_bytes()).hexdigest(), digest, source)

    def test_all_ten_assertion_bodies_unchanged(self):
        names = {'cryo_chamber': 'cryo', 'clone_lab': 'clone', 'data_archive': 'archive',
                 'biodome': 'biodome', 'xeno_lab': 'xeno', 'anomaly_lab': 'anomaly',
                 'bio_lab': 'bio', 'holographic_core': 'holo',
                 'med_center': 'med_center', 'med_office': 'med_office'}
        for identity, short in names.items():
            source = (ROOT / f'tests/playtest_{short}_room.gd').read_text(encoding='utf-8')
            expected = source.replace('extends "res://tests/playtest_underwater_life_support.gd"',
                                      'extends "res://tests/runtime_generated/room_support.gd"', 1)
            self.assertEqual((OUT / f'{identity}.gd').read_text(encoding='utf-8'), expected, identity)

    def test_support_body_unchanged(self):
        source = (ROOT / 'tests/playtest_underwater_life_support.gd').read_text(encoding='utf-8')
        expected = source.replace('extends "res://tests/playtest_nursery_art.gd"',
                                  'extends "res://tests/runtime_generated/room_base.gd"', 1)
        self.assertEqual((OUT / 'room_support.gd').read_text(encoding='utf-8'), expected)

    def test_drone_bay_bodies_unchanged(self):
        for identity in ['mining_drone_bay', 'salvage_drone_bay']:
            generated = OUT / f'{identity}.gd'
            self.assertTrue(generated.is_file(), f'Missing exported fixture: {identity}')
            original = (ROOT / f'tests/playtest_{identity}.gd').read_text(encoding='utf-8')
            expected = original.replace('extends "res://tests/playtest_underwater_life_support.gd"',
                                        'extends "res://tests/runtime_generated/room_support.gd"', 1)
            self.assertEqual(generated.read_text(encoding='utf-8'), expected)

    def test_repaired_foundation_bodies_unchanged(self):
        for identity, source, parent, target in [
            ('med_bay', 'playtest_med_bay.gd', 'playtest_underwater_life_support.gd', 'room_support.gd'),
            ('reactor', 'playtest_whole_room_station.gd', 'playtest_nursery_art.gd', 'room_base.gd'),
            ('reactor_effects', 'playtest_reactor_effects.gd', 'playtest_underwater_life_support.gd', 'room_support.gd'),
            ('reactor_lighting', 'playtest_reactor_lighting.gd', 'playtest_reactor_effects.gd', 'reactor_effects.gd'),
        ]:
            original = (ROOT / 'tests' / source).read_text(encoding='utf-8')
            expected = original.replace(f'extends "res://tests/{parent}"',
                                        f'extends "res://tests/runtime_generated/{target}"', 1)
            self.assertEqual((OUT / f'{identity}.gd').read_text(encoding='utf-8'), expected)

    def test_reactor_followups_are_dispatched(self):
        dispatch = (OUT / 'dispatch.gd').read_text(encoding='utf-8')
        for identity in ['reactor_effects', 'reactor_lighting']:
            entry = f'"{identity}": preload("res://tests/runtime_generated/{identity}.gd")'
            self.assertEqual(dispatch.count(entry), 1, identity)


if __name__ == '__main__':
    unittest.main()
