extends Node
# Generated by tools/build_room_export_fixture.py; edit the source fixture.
@onready var root = get_tree().root
func quit(code: int = 0) -> void: get_tree().quit(code)
const Service=preload("res://scripts/airlock_service.gd")
const Architects=preload("res://scripts/architects.gd")
const Save=preload("res://scripts/run_save.gd")
const View=preload("res://rooms/underwater/airlock-v1/airlock_view.gd")
const Cycle=preload("res://scripts/airlock_cycle.gd")
const CORE=Vector2i(20,20)
var OUT: String="res://output/airlock-review-%d" % OS.get_process_id()
var game
var failures:=0
var movement_samples:=0
var native:=false
var review_actor: String=""
var cell: Vector2i
func _init() -> void: call_deferred("run")
func check(value: bool,message: String) -> void:
	if not value:
		failures+=1
		if failures<20: push_error(message)
func settle() -> void:
	for i in range(4): await get_tree().process_frame
	var rendered: Array=[false]
	var observed: Callable=func(): rendered[0]=true
	RenderingServer.frame_post_draw.connect(observed)
	# Request the frame after settling, not before frames that may consume it.
	if is_instance_valid(game): game.grid_view.queue_redraw()
	for attempt in range(120):
		await get_tree().process_frame
		if rendered[0]: break
	RenderingServer.frame_post_draw.disconnect(observed)
	if not rendered[0]:
		check(false,"Airlock capture did not receive a rendered frame within 120 scene frames")
		quit(1)
func capture(label: String,station:=true) -> void:
	if not native: return
	var previous_scroll: int=game.grid_scroll.scroll_vertical
	game.grid_scroll.scroll_vertical=maxi(0,previous_scroll-roundi(30.0*game.get_cell_size()/384.0))
	game.grid_view.queue_redraw()
	await settle()
	if station: root.get_texture().get_image().save_png(OUT.path_join(label+"-station.png"))
	var margin: float=60.0*game.get_cell_size()/384.0
	var local:=Rect2(Vector2(cell)*game.get_cell_size()-Vector2(0,margin),Vector2.ONE*game.get_cell_size()+Vector2(0,margin))
	var screen: Rect2=root.get_stretch_transform()*game.grid_view.get_global_transform_with_canvas()*local
	root.get_texture().get_image().get_region(Rect2i(screen)).save_png(OUT.path_join(label+".png"))
	game.grid_scroll.scroll_vertical=previous_scroll
func reach_action(actor) -> void:
	for i in range(1600):
		if actor.helmet_action_active(): break
		game._update_test_walker(0.05)
		check(actor.can_stand(actor.foot),"Locker trip remains collision-free")
		movement_samples+=1
	check(actor.helmet_action_active(),"Walking reaches real locker and starts helmet action")

func exercise_cycle(id: String,q: int) -> void:
	var room: Dictionary=game.occupied[cell]
	var offset: Vector2i=[Vector2i.UP,Vector2i.RIGHT,Vector2i.DOWN,Vector2i.LEFT][q]
	game.wrecks.erase(cell+offset) # Clear only this fixture's exterior approach.
	game.occupied[cell+offset]={"id":"corridor"}
	check(not Cycle.request(game,cell,true),"Blocked exterior refuses outbound cycle")
	game.occupied.erase(cell+offset)
	check(Cycle.request(game,cell,true),"Outbound cycle accepted")
	check(not Cycle.request(game,cell,false),"Cannot override interlock mid-cycle")
	var held:=Cycle.state(room).duplicate()
	Cycle.advance(game,2)
	check(Cycle.state(room)==held,"Paused chamber holds")
	game.paused=false
	game.powered_room_cells.erase(cell)
	Cycle.advance(game,2)
	check(Cycle.state(room)==held,"Power loss holds chamber safely")
	game.powered_room_cells[cell]=true
	var seen: Dictionary={}
	for outward in [true,false]:
		if not outward: check(Cycle.request(game,cell,false),"Inbound cycle accepted")
		for i in range(81):
			Cycle.advance(game,0.1)
			room=game.occupied[cell]
			var p:=Cycle.pose(room)
			if id=="bill" and q==0 and i%2==0:
				await capture("motion-%03d" % (i if outward else i+81),false)
			check(not (p.inner>0 and p.outer>0),"Never open both interlocked doors")
			if p.inner>0: check(p.water==0 and p.pressure==0,"Inner door only opens dry at station pressure")
			if p.outer>0: check(p.water==1 and p.pressure==1,"Outer hatch only opens flooded at equal pressure")
			if not seen.has(p.phase):
				seen[p.phase]=true
				game.powered_room_cells.erase(cell)
				Cycle.advance(game,1)
				check(Cycle.pose(room)==p,"Every phase freezes on power loss")
				game.powered_room_cells[cell]=true
				room.suspended=true
				Cycle.advance(game,1)
				check(Cycle.pose(room)==p,"Every phase freezes when suspended")
				room.suspended=false
				if id=="bill": await capture("cycle-q%d-%s" % [q,p.phase])
				if q==0:
					check(Save.write(game,game.run_save_path)==OK,"Chamber phase saves to disk")
					check(await Save.restore(game,Save.read(game.run_save_path)),"Chamber phase restores from disk")
					game.tick_timer.stop()
					check(Cycle.pose(game.occupied[cell])==p,"Restore preserves water, pressure and both door apertures")
					game.paused=false
		check(Cycle.state(game.occupied[cell]).phase==("exterior" if outward else "dry"),"Chamber reaches safe endpoint")
	check(seen.size()==10,"All ten interlock phases exercised")
	var bad:=Save.capture(game).duplicate(true)
	for saved_room in bad.state.placed_rooms:
		if saved_room.id=="airlock": saved_room.airlock_cycle={"phase":"opening_inner","elapsed":INF}
	check(not await Save.restore(game,bad),"Invalid pressure checkpoint rejected before mutation")
	game.paused=true
class Card extends Node2D:
	var view
	func _draw() -> void:
		view.configure_embedded(0,[],false,0)
		draw_set_transform(Vector2(256,280),0,Vector2.ONE*1.04)
		draw_set_transform(Vector2.ZERO)
		view.render_into(self,Vector2(256,280),1.04)
func bake_card() -> void:
	var viewport:=SubViewport.new()
	viewport.size=Vector2i(512,512)
	viewport.transparent_bg=true
	viewport.render_target_update_mode=SubViewport.UPDATE_ALWAYS
	root.add_child(viewport)
	var view:=View.new()
	view.embedded=true
	view.hide()
	viewport.add_child(view)
	var card:=Card.new()
	card.view=view
	viewport.add_child(card)
	await settle()
	check(viewport.get_texture().get_image().save_png(OUT.path_join("card-candidate.png"))==OK,"Review card saved without publishing")
	viewport.queue_free()
func run() -> void:
	native=DisplayServer.get_name()!="headless"
	for arg in OS.get_cmdline_user_args():
		if arg.begins_with("--output="): OUT=arg.trim_prefix("--output=")
		if arg.begins_with("--capture-dir="): OUT=arg.trim_prefix("--capture-dir=").replace("\\","/")
		if arg.begins_with("--actor="): review_actor=arg.trim_prefix("--actor=")
	if not review_actor.is_empty() and not review_actor in Architects.IDS:
		push_error("Unknown Airlock review actor")
		quit(1)
		return
	if not (OUT.begins_with("res://output/") or (OUT.is_absolute_path() and not "://" in OUT)) or ".." in OUT or DirAccess.dir_exists_absolute(OUT):
		push_error("Airlock review requires a fresh output directory")
		quit(1)
		return
	if DirAccess.make_dir_recursive_absolute(OUT)!=OK:
		push_error("Cannot create Airlock evidence directory")
		quit(1)
		return
	game=load("res://scenes/main.tscn").instantiate()
	var prefix: String="user://airlock_test_%d" % OS.get_process_id()
	game.meta.save_path=prefix+".meta"
	game.run_save_path=prefix+".loop"
	game.Preferences.save_path=prefix+".cfg"
	root.add_child(game)
	get_tree().current_scene=game
	game.set_process(false)
	game.set_process_input(false)
	game.set_process_unhandled_input(false)
	game.set_process_unhandled_key_input(false)
	root.gui_disable_input=true
	game.tick_timer.stop()
	check(game.meta.unlocked_room_ids.has("airlock"),"Airlock is a starting blueprint")
	check(game.RunManagerScript.build_deck([],game.meta.unlocked_room_ids).has("airlock"),"Airlock enters normal draft")
	check(game.RoomDatabaseScript.get_room("airlock").cost.metal==6,"Paid airlock cost retained")
	if native:
		root.mode=Window.MODE_WINDOWED
		root.borderless=false
		root.size=Vector2i(1600,900)
	for id in Architects.IDS:
		if not review_actor.is_empty() and id!=review_actor: continue
		for q in range(4 if id=="bill" else 1):
			game.meta.unlocked_architect_ids[id]=true
			game.meta.selected_architect=id
			game._start_reboot_cycle()
			game.tick_timer.stop()
			Architects.advance_core(game,7)
			game.paused=true
			cell=CORE+[Vector2i.UP,Vector2i.RIGHT,Vector2i.DOWN,Vector2i.LEFT][q]
			game.wrecks.erase(cell)
			game._place_room("airlock",cell,true) # Free fixture placement; production cost checked above.
			game.occupied[cell].rotation=q
			game.powered_room_cells[cell]=true
			var actor=Architects.actor_for(game,id)
			actor.rebuild(game)
			var target:=Service.locker(game,cell)
			check(actor.can_stand(target.interaction_point),"Registered east-facing fitting point is reachable q%d" % q)
			var view=game.grid_view.airlock_view
			for prop in view.props:
				var envelope:=Rect2(-200,-200,400,400) if prop.id in ["outer_hatch","pressure_chamber"] else Rect2(-180,-180,360,360)
				check(envelope.encloses(view.prop_visual_bounds(prop)),"Airlock prop contained: "+prop.id)
				if prop.id=="outer_hatch":
					var bounds: Rect2=view.prop_visual_bounds(prop)
					check(bounds==view.turned_rect(Rect2(-44,-200,88,24)),"Cutaway hatch remains on rotated exterior sill")
			var exterior_wall: Rect2=view.turned_rect(Rect2(-192,-200,384,16))
			var segments: Array=view.exterior_wall_segments(exterior_wall)
			check(segments.size()==2,"Exterior hull splits at hatch")
			var aperture: Rect2=view.turned_rect(Rect2(-36,-200,72,16))
			for segment in segments:
				check(not segment.intersects(aperture),"No solid hull remains behind open hatch")
			check(view.exterior_wall_segments(view.turned_rect(Rect2(-192,184,384,16))).size()==1,"Opposite station wall is unchanged")
			check(game.get_room_doors(game.occupied[cell]).size()==1,"Only dry entry is a station connection")
			check(Service.request(game,id,cell),"Real locker accepts selected architect")
			check(Service.busy(game,cell),"Travelling crew reserves locker")
			check(not Service.request(game,id,cell),"Repeated click does not restart trip")
			check(not actor.helmet_equipped,"No helmet granted before arrival")
			if q==0:
				check(Save.write(game,game.run_save_path)==OK,"Pending locker trip saves")
				check(await Save.restore(game,Save.read(game.run_save_path)),"Pending locker trip restores")
				game.tick_timer.stop()
				actor=Architects.actor_for(game,id)
			reach_action(actor)
			check(actor.foot.distance_to(target.interaction_point)<=12,"Action occurs beside actual locker shelf")
			if native:
				game.selected_card_id=""
				game.selected_room_cell=cell
				game._refresh_all()
				game._set_grid_zoom(0.72)
				await settle()
				game.inspector_focus_button.set_meta("cell",cell)
				game._focus_inspected_room()
				game.grid_view.room_light_levels[cell]=1.0
				await capture("%s-q%d-start" % [id,q])
			var before: float=actor.timer
			check(Service.helmet_on_shelf(game,cell),"Staged helmet visible before pickup")
			await capture("%s-q%d-shelf-before-grasp" % [id,q])
			actor.timer=2.14-0.321
			if Service.helmet_on_shelf(game,cell):
				for peer_id in Architects.IDS:
					var peer=Architects.actor_for(game,peer_id)
					print("SHELF DIAGNOSTIC ",JSON.stringify({"selected":id,"quarter":q,"peer":peer_id,"same_controller":actor==peer,"active":peer.active,"dead":peer.dead,"state":peer.state,"timer":peer.timer,"cell":str(peer.cell_at(peer.foot)),"target_cell":str(cell)}))
			check(not Service.helmet_on_shelf(game,cell),"Shelf helmet hides at grasp")
			await capture("%s-q%d-shelf-after-grasp" % [id,q])
			actor.timer=before
			game._process(0.2)
			check(actor.timer==before,"Pause holds equipment action")
			game._update_test_walker(0.35)
			if q==0:
				check(Save.write(game,game.run_save_path)==OK,"Mid-action saves")
				check(await Save.restore(game,Save.read(game.run_save_path)),"Mid-action restores")
				game.tick_timer.stop()
				actor=Architects.actor_for(game,id)
			await capture("%s-q%d-fitting" % [id,q])
			game._update_test_walker(5)
			check(actor.helmet_equipped and not actor.helmet_action_active(),"Helmet appears on completion")
			await capture("%s-q%d-equipped" % [id,q])
			check(Service.request(game,id,cell),"Return helmet action accepted")
			reach_action(actor)
			var return_before: float=actor.timer
			actor.timer=2.24-1.899
			check(not Service.helmet_on_shelf(game,cell),"No shelf duplicate before release")
			await capture("%s-q%d-shelf-before-release" % [id,q])
			actor.timer=2.24-1.901
			check(Service.helmet_on_shelf(game,cell),"Shelf helmet persists after release")
			await capture("%s-q%d-shelf-after-release" % [id,q])
			if q==0:
				var release_timer: float=actor.timer
				print("RELEASE CHECKPOINT begin ",id," ticks=",Time.get_ticks_msec())
				check(Save.write(game,game.run_save_path)==OK,"Post-release action writes to disk")
				print("RELEASE CHECKPOINT written ",id," ticks=",Time.get_ticks_msec())
				check(await Save.restore(game,Save.read(game.run_save_path)),"Post-release action restores")
				print("RELEASE CHECKPOINT restored ",id," ticks=",Time.get_ticks_msec())
				game.tick_timer.stop()
				actor=Architects.actor_for(game,id)
				check(is_equal_approx(actor.timer,release_timer) and actor.helmet_action_active(),"Post-release action resumes same time")
				check(Service.helmet_on_shelf(game,cell),"Restored release keeps shelf helmet visible")
			actor.timer=return_before
			game._update_test_walker(0.2)
			await capture("%s-q%d-removing" % [id,q])
			game.powered_room_cells.erase(cell)
			game._update_test_walker(0.05)
			check(actor.helmet_equipped and not actor.helmet_action_active(),"Power loss cancels removal without changing gear")
			check(not Service.request(game,id,cell),"Offline airlock refuses equipment service")
			game.powered_room_cells[cell]=true
			check(Service.request(game,id,cell),"Service resumes after power returns")
			reach_action(actor)
			game._update_test_walker(5)
			check(not actor.helmet_equipped,"Returned helmet clears equipped state")
			await capture("%s-q%d-returned" % [id,q])
			await exercise_cycle(id,q)
	if native:
		await bake_card()
		var card_image:=Image.new()
		check(card_image.load_png_from_buffer(FileAccess.get_file_as_bytes(OUT.path_join("card-candidate.png")))==OK,"Review card loads")
		game.card_textures.airlock=ImageTexture.create_from_image(card_image)
		game._refresh_all()
		for width in [1280,1600,2560]:
			root.size=Vector2i(width,roundi(width*9.0/16))
			await settle()
			game.inspector_focus_button.set_meta("cell",cell)
			game._focus_inspected_room()
			await capture("inspector-%d" % width)
			var controls=game.find_child("ControlsPanel",true,false)
			var sidebar=game.find_child("SideScroll",true,false)
			check(controls.get_global_rect().end.y<=sidebar.get_global_rect().end.y+1,"Locker controls fit within the sidebar viewport")
	game.free()
	for suffix in [".meta",".meta.bak",".loop",".loop.bak",".cfg"]:
		if FileAccess.file_exists(prefix+suffix): DirAccess.remove_absolute(ProjectSettings.globalize_path(prefix+suffix))
	print("AIRLOCK %s: %s, %d travel samples, equipment/return, ten interlock phases, power interruption, pause, disk saves and UI" % ["PASS" if failures==0 else "FAIL","all three architects, four rotations" if review_actor.is_empty() else review_actor+" focused review",movement_samples])
	quit(0 if failures==0 else 1)
