extends Node
# Generated by tools/build_room_export_fixture.py; edit the source fixture.
@onready var root = get_tree().root
var current_scene: Node
func quit(code: int = 0) -> void: get_tree().quit(code)
const MainScene = preload("res://scenes/main.tscn")
const Geometry = preload("res://tools/modular_room_geometry.gd")
var game
var capture_dir := ""
var viewport_width := 1600
var failures := 0

func _init() -> void:
	for arg in OS.get_cmdline_user_args():
		if arg.begins_with("--capture-dir="):
			capture_dir = arg.trim_prefix("--capture-dir=")
		if arg.begins_with("--viewport-width="):
			viewport_width = int(arg.trim_prefix("--viewport-width="))
	call_deferred("run")

func settle() -> void:
	for unused in range(4):
		await get_tree().process_frame
	await RenderingServer.frame_post_draw

func capture(name: String) -> void:
	var negative_overlay: bool="--negative-menu-overlay" in OS.get_cmdline_user_args() and name=="station-q0"
	if negative_overlay: game._toggle_menu()
	game.grid_view.queue_redraw()
	await settle()
	# Art-state comparisons are invalid when unrelated UI covers the room.
	# Do not silently close it: preserve the contaminated frame and fail explicitly.
	expect(not game.menu_open,"Capture obstructed by game menu: "+name)
	var frame := root.get_texture().get_image()
	var expected_size := Vector2i(viewport_width,roundi(viewport_width*9.0/16.0))
	expect(frame.get_size()==expected_size,"Capture dimensions mismatch: requested %s, actual %s"%[expected_size,frame.get_size()])
	frame.save_png(capture_dir.path_join(name + ".png"))
	var state:=FileAccess.open(capture_dir.path_join(name+".state.json"),FileAccess.WRITE)
	state.store_string(JSON.stringify({"capture":name,"menu_open":game.menu_open,
		"paused":game.paused,"visual_time":game.visual_time_seconds,
		"scroll_x":game.grid_scroll.scroll_horizontal,"scroll_y":game.grid_scroll.scroll_vertical,
		"grid_zoom":game.grid_zoom,
		"crew_active":[game.bill_npc.active,game.veld_npc.active,game.branforth_npc.active],
		"crew_present":[game.Architects.present(game,"bill"),game.Architects.present(game,"veld"),game.Architects.present(game,"branforth")],
		"viewport_width":root.size.x,"viewport_height":root.size.y},"\t"))
	if negative_overlay:
		state.close()
		quit(1 if failures>0 else 0)
		await get_tree().process_frame

func expect(value: bool, message: String) -> void:
	if not value:
		failures += 1
		push_error(message)

func verify_input_isolation() -> void:
	expect(not game.menu_open and game.paused,"Art input isolation starts from an unobstructed paused baseline")
	expect(not game.is_processing_input() and not game.is_processing_unhandled_input() and root.gui_disable_input,"Art fixture input gates remain disabled")
	var camera:=Vector2i(game.grid_scroll.scroll_horizontal,game.grid_scroll.scroll_vertical)
	var zoom: float=game.grid_zoom
	for key in [KEY_ESCAPE,KEY_W,KEY_SPACE]:
		var event:=InputEventKey.new()
		event.keycode=key
		event.physical_keycode=key
		event.pressed=true
		Input.parse_input_event(event)
		await settle()
		event.pressed=false
		Input.parse_input_event(event)
		await settle()
		expect(not game.menu_open and game.paused,"Injected key must not alter art-fixture menu/pause")
		expect(camera==Vector2i(game.grid_scroll.scroll_horizontal,game.grid_scroll.scroll_vertical) and zoom==game.grid_zoom,"Injected key must not move art-fixture camera")
	print("ART INPUT ISOLATION: Escape/W/Space injected and released; menu, pause and camera checked")

func room_pixels(cell: Vector2i) -> Image:
	var cell_size: float = game.get_cell_size()
	var local_rect := Rect2(Vector2(cell) * cell_size, Vector2.ONE * cell_size)
	# Viewport texture pixels include canvas_items stretch, unlike canvas coordinates.
	var screen_rect: Rect2 = root.get_stretch_transform() * game.grid_view.get_global_transform_with_canvas() * local_rect
	var frame: Image = root.get_texture().get_image()
	return frame.get_region(Rect2i(screen_rect.intersection(Rect2(Vector2.ZERO, frame.get_size()))))

func verify_motion_and_routes() -> void:
	for q in range(4):
		game.placed_rooms.clear()
		game.occupied.clear()
		game.powered_room_cells.clear()
		game.unpowered_room_cells.clear()
		var first := Vector2i(20, 20)
		var offset := Vector2i(Geometry.turn(Vector2.RIGHT, q))
		var second := first + offset
		game._place_room("mycelium_nursery", first, true)
		game._place_room("mycelium_nursery", second, true)
		for cell in [first, second]:
			game.occupied[cell].rotation = q
			game.powered_room_cells[cell] = true
		game.test_walker_cell = Vector2i(-1, -1)
		game.hover_cell = Vector2i(-1, -1)
		game._refresh_all()
		await settle()
		game._fit_station_view()
		await settle()
		for running in [true, false]:
			if not running:
				game.powered_room_cells.clear()
			game.visual_time_seconds = 0.2
			await capture("motion-q%d-%s-a" % [q, running])
			var before := room_pixels(first)
			before.save_png(capture_dir.path_join("crop-q%d-%s-a.png" % [q, running]))
			game.visual_time_seconds = 1.1
			await capture("motion-q%d-%s-b" % [q, running])
			room_pixels(first).save_png(capture_dir.path_join("crop-q%d-%s-b.png" % [q, running]))
			expect((before.get_data() != room_pixels(first).get_data()) == running, "Station machinery state pixels q%d running=%s" % [q, running])
		game.test_walker_cell = first
		game.test_walker_next_cell = second
		game.test_walker_previous_cell = Vector2i(-1, -1)
		game.test_walker_state = "walk"
		var layout := [{"cell": Vector2i.ZERO, "rotation": q, "kind": 0}, {"cell": offset, "rotation": q, "kind": 0}]
		# Check the actual current renderer's fixed-facing footprints, not the
		# historical directional proxy recipe that previously occupied this slot.
		var furnishings: Array = []
		expect(game.grid_view.nursery_view.quarter==q,"Embedded layout rotation matches room")
		for entry in layout:
			for prop in game.grid_view.nursery_view.props:
				var rect: Rect2 = prop.rect
				rect.position += Vector2(entry.cell)*Geometry.CELL
				furnishings.append({"rect":rect})
		var edges := Geometry.edges(layout)
		for step in range(0 if "--state-only" in OS.get_cmdline_user_args() else 101):
			game.test_walker_progress = step / 100.0
			var foot: Vector2 = game.get_test_walker_position() + Vector2(0, game.get_cell_size() * 0.038)
			var local_foot: Vector2 = (foot - game._cell_center(first)) * (384.0 / game.get_cell_size())
			expect(Geometry.can_stand(local_foot, layout, furnishings, edges), "Real walker route collides at q%d step%d" % [q, step])
			if step in [0, 25, 45, 50, 55, 75, 100]:
				await capture("walk-q%d-%03d" % [q, step])
		game.test_walker_next_cell = Vector2i(-1, -1)
		game.test_walker_state = "idle"
		await capture("paused-q%d-a" % q)
		var paused_frame := room_pixels(first)
		await capture("paused-q%d-b" % q)
		expect(paused_frame.get_data() == room_pixels(first).get_data(), "Actual paused station frames remain equal")
	print("STATION STATE CHECKS: 8 motion comparisons, 4 paused pairs; ","legacy walker skipped; use --nursery-tour for current movement" if "--state-only" in OS.get_cmdline_user_args() else "404 legacy progress samples, not current-controller movement evidence")

func capture_mixed_neighbors() -> void:
	for q in [0, 1]:
		game.placed_rooms.clear()
		game.occupied.clear()
		game.powered_room_cells.clear()
		game.unpowered_room_cells.clear()
		var first := Vector2i(20, 20)
		var offset := Vector2i(Geometry.turn(Vector2.RIGHT, q))
		game._place_room("mycelium_nursery", first, true)
		game._place_room("bio_lab", first + offset, true)
		game.occupied[first].rotation = q
		game.occupied[first + offset].rotation = q
		game.test_walker_cell = first
		game.test_walker_next_cell = first + offset
		game.test_walker_progress = 0.5
		game.test_walker_state = "walk"
		game._refresh_all()
		await settle()
		game._fit_station_view()
		await capture("mixed-bio-lab-q%d" % q)

func evidence_subject() -> String: return "mycelium_nursery"

func run() -> void:
	if capture_dir.is_empty() or DirAccess.dir_exists_absolute(capture_dir):
		push_error("Use a new --capture-dir for nursery scene evidence")
		quit(1)
		return
	DirAccess.make_dir_recursive_absolute(capture_dir)
	game = MainScene.instantiate()
	# Do not import the player's fullscreen/accessibility settings into art evidence.
	# This path is fixture-local and is never saved by this harness.
	game.Preferences.save_path="user://brine_art_settings_%d.cfg"%OS.get_process_id()
	# Concurrent art sessions must not overwrite or remove each other's fixture save.
	game.meta.save_path = "user://brine_nursery_art_fixture_%d_%d.json" % [viewport_width,OS.get_process_id()]
	game.meta.discovered_synergy_ids.clear()
	game.meta.stabilized_synergy_ids.clear()
	game.meta.unlocked_room_ids.clear()
	game.rng.seed = 9135
	root.add_child(game)
	get_tree().current_scene = game
	# Close the initialization window before any rendering/window-size awaits.
	# Pausing simulation alone does not prevent Escape from opening the menu.
	game.set_process(false)
	game.set_process_input(false)
	game.set_process_unhandled_input(false)
	game.set_process_unhandled_key_input(false)
	root.gui_disable_input=true
	root.mode = Window.MODE_WINDOWED
	root.borderless=false
	await get_tree().process_frame
	root.size = Vector2i(viewport_width, roundi(viewport_width * 9.0 / 16.0))
	await settle()
	game.pending_doctrines.assign(["biosphere", "recovery"])
	game._confirm_doctrines()
	game.orbit.rng.seed = 9135
	game._set_paused(true)
	# This is a scripted art-state fixture, not an interactive-input playtest.
	# Main's _process polls held camera keys even while gameplay is paused.
	# Economy, walker steps and visual clocks are advanced explicitly by fixtures.
	game.set_process(false)
	game.set_process_unhandled_input(false)
	root.gui_disable_input=true
	game.placed_rooms.clear()
	game.occupied.clear()
	game.powered_room_cells.clear()
	game.unpowered_room_cells.clear()
	game._place_room("mycelium_nursery", Vector2i(20, 20), true)
	game._place_room("mycelium_nursery", Vector2i(21, 20), true)
	game.powered_room_cells[Vector2i(20, 20)] = true
	game.powered_room_cells[Vector2i(21, 20)] = true
	game.hand.assign(["mycelium_nursery", "hydroponics_bay", "med_bay"])
	game.selected_card_id = ""
	game.hover_cell = Vector2i(20, 20)
	game._refresh_all()
	await settle()
	game._fit_station_view()
	await settle()
	if "--exercise-input-isolation" in OS.get_cmdline_user_args(): await verify_input_isolation()
	if not game.card_textures.has("mycelium_nursery"):
		push_error("Nursery card missing from actual consumer")
		quit(1)
		return
	for q in range(4):
		game.occupied[Vector2i(20, 20)].rotation = q
		game._check_synergies()
		await capture("station-q%d" % q)
	game.occupied[Vector2i(20, 20)].rotation = 0
	game.powered_room_cells.erase(Vector2i(20, 20))
	game.unpowered_room_cells[Vector2i(20, 20)] = true
	await capture("station-offline")
	await verify_motion_and_routes()
	await capture_mixed_neighbors()
	var fixture_save: String = game.meta.save_path
	game.free()
	if FileAccess.file_exists(fixture_save):
		DirAccess.remove_absolute(ProjectSettings.globalize_path(fixture_save))
	print("ROOM SCENE %s [%s]: %d assertion failures; coverage is defined by subject-specific output; visual review separate" % ["PASS" if failures == 0 else "FAIL", evidence_subject(), failures])
	quit(0 if failures == 0 else 1)
