from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[2]
data=json.loads((ROOT/'output/crew-action-review.json').read_text())
html='''<!doctype html><html><meta charset="utf-8"><title>Crew action review</title><style>
body{background:#111e23;color:#dfebea;font:16px system-ui;margin:32px}h1{font-size:28px}button,select{background:#263b43;color:#e1f6ef;border:1px solid #52737b;border-radius:7px;padding:9px;margin:4px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(420px,1fr));gap:16px;margin-top:22px}.card{background:#1b2b32;border:1px solid #385059;border-radius:12px;padding:18px}.pair{display:flex;justify-content:space-around}canvas{width:192px;height:192px;image-rendering:pixelated}small{color:#a5bcbc}h2{font-size:18px;margin:0 0 10px}.label{text-align:center;font-size:13px;color:#9ab2b9}
</style><h1>Crew actions</h1><p>Salvage, swimming transitions, torch handling, cargo, and directional work.</p>
<select id=action></select><select id=facing><option value=all>All directions</option><option>east</option><option>south</option><option>west</option><option>north</option></select><button id=play>Pause</button><button id=scale>Station scale</button><small>One-shot actions repeat here for review.</small><main></main><script>
const data=DATA;let paused=false,time=0,last=performance.now(),views=[],station=false;
const titles={'salvage':'Underwater salvage','swim-start':'Start swimming','swim-stop':'Stop swimming','swim-turn':'Turn while swimming','torch-draw':'Draw blowtorch','torch-stow':'Stow blowtorch','carry':'Carry cargo','swim-carry':'Swim with cargo','unload':'Unload cargo','interact':'Use equipment','kneel':'Kneel down','repair':'Repair / inspect','stand':'Stand up'};
const action=document.querySelector('#action'),facing=document.querySelector('#facing');for(const key in titles)action.add(new Option(titles[key],key));
function refresh(){views=[];time=0;const main=document.querySelector('main');main.innerHTML='';for(const [actor,clips] of Object.entries(data))for(const clip of clips){const family=clip.key.startsWith('swim-turn-')?'swim-turn':clip.key.slice(0,clip.key.lastIndexOf('-'));if(family!==action.value||facing.value!=='all'&&!clip.key.endsWith('-'+facing.value))continue;const card=document.createElement('section');card.className='card';const h=document.createElement('h2');h.textContent=({bill:'Major Bill',veld:'Dr. Veld',branforth:'Chief Branforth'})[actor]+' / '+clip.key.slice(family.length+1).replaceAll('-',' to ');card.append(h);const pair=document.createElement('div');pair.className='pair';card.append(pair);clip.files.forEach((file,index)=>{const wrap=document.createElement('div'),c=document.createElement('canvas');c.width=c.height=128;c.style.width=c.style.height=station?'128px':'192px';wrap.append(c);const label=document.createElement('div');label.className='label';label.textContent=index?'Helmet fitted':'Without helmet';wrap.append(label);pair.append(wrap);const img=new Image();img.src=file;views.push({c,img,clip});});main.append(card);}}
action.onchange=facing.onchange=refresh;document.querySelector('#play').onclick=e=>{paused=!paused;e.target.textContent=paused?'Play':'Pause'};document.querySelector('#scale').onclick=e=>{station=!station;e.target.textContent=station?'Close-up':'Station scale';document.querySelectorAll('canvas').forEach(c=>c.style.width=c.style.height=station?'128px':'192px')};
function tick(now){if(!paused)time+=now-last;last=now;for(const {c,img,clip} of views){if(!img.complete||!img.naturalWidth)continue;const total=clip.durations.reduce((a,b)=>a+b,0);let t=time%(total+(clip.loop?0:600)),i=0;while(i<clip.durations.length-1&&t>=clip.durations[i])t-=clip.durations[i++];const ctx=c.getContext('2d');ctx.clearRect(0,0,128,128);ctx.drawImage(img,i*128,0,128,128,0,0,128,128);}requestAnimationFrame(tick)}refresh();requestAnimationFrame(tick);
</script></html>'''.replace('DATA',json.dumps(data))
(ROOT/'output/crew-actions-review.html').write_text(html,encoding='utf-8')
print(sum(len(v) for v in data.values()),'clips in moving review')
