extends RefCounted

# Card art baked from the current room designs by tools/bake_room_cards_v2.gd (owner playtest,
# Sept 17). Corridors keep their polished cards. Re-run the tool after redressing rooms.
const PATHS := {
	"cold_store": "res://assets/room-cards-v2/cold_store.png",
	"galley": "res://assets/room-cards-v2/galley.png",
	"salvage_workshop": "res://assets/room-cards-v2/salvage_workshop.png",
	"observation_room": "res://assets/room-cards-v2/observation_room.png",
	"current_turbine": "res://assets/room-cards-v2/current_turbine.png",
	"biomass_digester": "res://assets/room-cards-v2/biomass_digester.png",
	"heat_recovery": "res://assets/room-cards-v2/heat_recovery.png",
	"airlock": "res://assets/room-cards-v2/airlock.png",
	"pressure_control": "res://assets/room-cards-v2/pressure_control.png",
	"listening_post": "res://assets/room-cards-v2/listening_post.png",
	"isolation_vault": "res://assets/room-cards-v2/isolation_vault.png",
	"construction_drone_bay": "res://assets/room-cards-v2/construction_drone_bay.png",
	"mycelium_nursery": "res://assets/room-cards-v2/mycelium_nursery.png",
	"tidal_condenser": "res://assets/room-cards-v2/tidal_condenser.png",
	"gravity_loom": "res://assets/room-cards-v2/gravity_loom.png",
	"battery_array": "res://assets/room-cards-v2/battery_array.png",
	"biodome": "res://assets/room-cards-v2/biodome.png",
	"clone_lab": "res://assets/room-cards-v2/clone_lab.png",
	"brine_core": "res://assets/room-cards-v2/brine_core.png",
	"crew_hab": "res://assets/room-cards-v2/crew_hab.png",
	"cryo_chamber": "res://assets/room-cards-v2/cryo_chamber.png",
	"data_archive": "res://assets/room-cards-v2/data_archive.png",
	"hydroponics_bay": "res://assets/room-cards-v2/hydroponics_bay.png",
	"life_support": "res://assets/room-cards-v2/life_support.png",
	"mining_drone_bay": "res://assets/room-cards-v2/mining_drone_bay.png",
	"ore_refinery": "res://assets/room-cards-v2/ore_refinery.png",
	"quarantine_cell": "res://assets/room-cards-v2/quarantine_cell.png",
	"reactor": "res://assets/room-cards-v2/reactor.png",
	"research_lab": "res://assets/room-cards-v2/research_lab.png",
	"salvage_drone_bay": "res://assets/room-cards-v2/salvage_drone_bay.png",
	"solar_array": "res://assets/room-cards-v2/solar_array.png",
	"storage_bay": "res://assets/room-cards-v2/storage_bay.png",
	"med_bay": "res://assets/room-cards-v2/med_bay.png",
	"xeno_lab": "res://assets/room-cards-v2/xeno_lab.png",
	"anomaly_lab": "res://assets/room-cards-v2/anomaly_lab.png",
	"bio_lab": "res://assets/room-cards-v2/bio_lab.png",
	"command_center": "res://assets/room-cards-v2/command_center.png",
	"tee_corridor": "res://assets/corridor-polish-v3/cards/tee_corridor.png",
	"corridor": "res://assets/corridor-polish-v3/cards/corridor.png",
	"corner": "res://assets/corridor-polish-v3/cards/corner.png",
	"crew_lounge": "res://assets/room-cards-v2/crew_lounge.png",
	"holographic_core": "res://assets/room-cards-v2/holographic_core.png",
	"maintenance_bay": "res://assets/room-cards-v2/maintenance_bay.png",
	"med_center": "res://assets/room-cards-v2/med_center.png",
	"med_office": "res://assets/room-cards-v2/med_office.png",
	"radio_lab": "res://assets/room-cards-v2/radio_lab.png",
	"shield_generator": "res://assets/room-cards-v2/shield_generator.png"
}
