extends RefCounted
class_name RoomDatabase

const CATEGORY_COLORS := {
	"Core": Color("#c8fbff"),
	"Engineering": Color("#e6c84f"),
	"Science": Color("#4f8fe6"),
	"Bio": Color("#57c879"),
	"Crew": Color("#e58a45"),
	"Medical": Color("#43d2c6"),
	"Drone": Color("#9aa2a8"),
	"Security": Color("#d34e58"),
	"Anomaly": Color("#9c5de8"),
	"Derelict": Color("#9b6941")
}

const RESOURCE_ICONS := {
	"metal": "□",
	"power": "⚡",
	"oxygen": "○",
	"water": "≈",
	"food": "◆",
	"data": "✦",
	"biomass": "✦",
	"rare_minerals": "◆",
	"integrity": "◇",
	"crew": "▣",
	"corruption": "☣"
}

const STARTING_UNLOCKS := [
	"solar_array",
	"reactor",
	"mining_drone_bay",
	"hydroponics_bay",
	"life_support",
	"crew_hab",
	"research_lab",
	"storage_bay",
	"med_bay",
	"quarantine_cell",
	"corridor",
	"corner"
]

const LAYOUTS := {
	"layout_01_tee": {"doors": ["west", "east", "south"], "path": "tee"},
	"layout_02_straight": {"doors": ["north", "south"], "path": "straight"},
	"layout_03_straight_ew": {"doors": ["west", "east"], "path": "straight"},
	"layout_04_corner": {"doors": ["west", "south"], "path": "elbow"},
	"layout_05_cross": {"doors": ["north", "east", "south", "west"], "path": "cross"},
	"layout_06_core": {"doors": ["north", "east", "south", "west"], "path": "perimeter"},
	"layout_dead_south": {"doors": ["south"], "path": "dead"},
	"layout_reactor_cross": {"doors": ["north", "east", "south", "west"], "path": "perimeter"},
	"tee_south": {"doors": ["west", "east", "south"], "path": "tee"},
	"vertical": {"doors": ["north", "south"], "path": "straight"},
	"dead_south": {"doors": ["south"], "path": "dead"},
	"elbow_north_west": {"doors": ["west", "south"], "path": "elbow"},
	"cross": {"doors": ["north", "east", "south", "west"], "path": "cross"},
	"ring_cross": {"doors": ["north", "east", "south", "west"], "path": "ring"}
}

static func all_rooms() -> Dictionary:
	return {
		"brine_core": {
			"id": "brine_core",
			"display_name": "BRINE Core",
			"category": "Core",
			"rarity": "core",
			"cost": {},
			"size": Vector2i.ONE,
			"production": {"data": 1},
			"consumption": {"power": 1},
			"tags": ["core", "data", "powered"],
			"layout": "layout_06_core",
			"description": "Damaged AI heart of the station. Produces Data, but must stay powered.",
			"unlocked": true
		},
		"solar_array": {
			"id": "solar_array",
			"display_name": "Solar Array",
			"category": "Engineering",
			"rarity": "common",
			"cost": {"metal": 4},
			"size": Vector2i.ONE,
			"production": {"power": 3},
			"consumption": {},
			"tags": ["power", "engineering"],
			"layout": "layout_04_corner",
			"description": "Passive solar collection. Steady Power income.",
			"unlocked": true
		},
		"reactor": {
			"id": "reactor",
			"display_name": "Reactor",
			"category": "Engineering",
			"rarity": "common",
			"cost": {"metal": 8, "rare_minerals": 1},
			"size": Vector2i.ONE,
			"production": {"power": 6},
			"consumption": {},
			"tags": ["power", "reactor", "engineering"],
			"layout": "layout_reactor_cross",
			"description": "High output Power. Future meltdown risk lives here.",
			"unlocked": true
		},
		"battery_array": {
			"id": "battery_array",
			"display_name": "Battery Array",
			"category": "Engineering",
			"rarity": "uncommon",
			"cost": {"metal": 6, "data": 2},
			"size": Vector2i.ONE,
			"production": {},
			"consumption": {},
			"storage": {"power": 12},
			"tags": ["power_storage", "battery", "engineering"],
			"layout": "layout_05_cross",
			"description": "Adds Power reserve capacity and buffers Reactor surges.",
			"unlocked": false
		},
		"mining_drone_bay": {
			"id": "mining_drone_bay",
			"display_name": "Mining Drone Bay",
			"category": "Drone",
			"rarity": "common",
			"cost": {"metal": 6, "power": 1},
			"size": Vector2i.ONE,
			"production": {"metal": 2},
			"consumption": {"power": 1},
			"tags": ["drone", "mining", "metal"],
			"layout": "layout_02_straight",
			"description": "Dispatches mining drones toward asteroid POIs.",
			"unlocked": true
		},
		"salvage_drone_bay": {
			"id": "salvage_drone_bay",
			"display_name": "Salvage Drone Bay",
			"category": "Drone",
			"rarity": "common",
			"cost": {"metal": 5, "power": 1},
			"size": Vector2i.ONE,
			"production": {"metal": 1, "data": 1},
			"consumption": {"power": 1},
			"tags": ["drone", "salvage", "derelict"],
			"layout": "layout_02_straight",
			"description": "Recovers Metal and Data from derelict POIs.",
			"unlocked": true
		},
		"hydroponics_bay": {
			"id": "hydroponics_bay",
			"display_name": "Hydroponics Bay",
			"category": "Bio",
			"rarity": "common",
			"cost": {"metal": 5, "biomass": 1},
			"size": Vector2i.ONE,
			"production": {"food": 2, "oxygen": 1, "biomass": 1},
			"consumption": {"power": 1},
			"tags": ["bio", "food", "oxygen", "plants"],
			"layout": "layout_05_cross",
			"description": "Grows food, oxygen, and a little Biomass.",
			"unlocked": true
		},
		"life_support": {
			"id": "life_support",
			"display_name": "Life Support",
			"category": "Bio",
			"rarity": "common",
			"cost": {"metal": 5, "power": 1},
			"size": Vector2i.ONE,
			"production": {"oxygen": 3},
			"consumption": {"power": 1},
			"tags": ["oxygen", "bio", "engineering", "medical_support"],
			"layout": "layout_05_cross",
			"description": "Stabilizes Oxygen. Vital before waking crew.",
			"unlocked": true
		},
		"crew_hab": {
			"id": "crew_hab",
			"display_name": "Crew Hab",
			"category": "Crew",
			"rarity": "common",
			"cost": {"metal": 6, "oxygen": 2, "food": 2},
			"size": Vector2i.ONE,
			"production": {},
			"consumption": {},
			"tags": ["crew", "hab"],
			"layout": "layout_01_tee",
			"description": "Adds crew capacity. New cycle grants one survivor if life is stable.",
			"unlocked": true
		},
		"research_lab": {
			"id": "research_lab",
			"display_name": "Research Lab",
			"category": "Science",
			"rarity": "common",
			"cost": {"metal": 6, "power": 1},
			"size": Vector2i.ONE,
			"production": {"data": 2},
			"consumption": {"power": 1},
			"tags": ["science", "data", "crew_bonus"],
			"layout": "layout_dead_south",
			"description": "Produces Data. Scientists improvise if any crew are alive.",
			"unlocked": true
		},
		"cryo_chamber": {
			"id": "cryo_chamber",
			"display_name": "Cryo Chamber",
			"category": "Medical",
			"rarity": "rare",
			"cost": {"metal": 8, "data": 4},
			"size": Vector2i.ONE,
			"production": {},
			"consumption": {"power": 1},
			"tags": ["medical", "derelict", "survivor"],
			"layout": "layout_02_straight",
			"description": "A damaged pod. With support nearby, survivors may wake.",
			"unlocked": false
		},
		"clone_lab": {
			"id": "clone_lab",
			"display_name": "Clone Lab",
			"category": "Medical",
			"rarity": "rare",
			"cost": {"metal": 10, "data": 8, "biomass": 8},
			"size": Vector2i.ONE,
			"production": {},
			"consumption": {"power": 2, "biomass": 1, "data": 1},
			"tags": ["medical", "bio", "clone"],
			"layout": "layout_01_tee",
			"description": "Creates clone crew from Biomass and Data.",
			"unlocked": false
		},
		"quarantine_cell": {
			"id": "quarantine_cell",
			"display_name": "Quarantine Cell",
			"category": "Security",
			"rarity": "uncommon",
			"cost": {"metal": 7, "data": 2},
			"size": Vector2i.ONE,
			"production": {},
			"consumption": {"power": 1},
			"tags": ["security", "medical", "containment"],
			"layout": "layout_03_straight_ew",
			"description": "Reduces hostile or anomalous spread risk.",
			"unlocked": false
		},
		"data_archive": {
			"id": "data_archive",
			"display_name": "Data Archive",
			"category": "Science",
			"rarity": "uncommon",
			"cost": {"metal": 5, "data": 8},
			"size": Vector2i.ONE,
			"production": {"data": 1},
			"consumption": {"power": 1},
			"storage": {"data": 40},
			"tags": ["science", "data", "archive"],
			"layout": "layout_06_core",
			"description": "Boosts Data storage and research indexing.",
			"unlocked": false
		},
		"ore_refinery": {
			"id": "ore_refinery",
			"display_name": "Ore Refinery",
			"category": "Engineering",
			"rarity": "uncommon",
			"cost": {"metal": 8, "power": 1},
			"size": Vector2i.ONE,
			"production": {"metal": 1},
			"consumption": {"power": 1},
			"storage": {"metal": 40, "rare_minerals": 10},
			"tags": ["engineering", "metal", "refinery"],
			"layout": "layout_02_straight",
			"description": "Improves Metal output from Mining Drone Bays.",
			"unlocked": true
		},
		"storage_bay": {
			"id": "storage_bay",
			"display_name": "Storage Bay",
			"category": "Engineering",
			"rarity": "common",
			"cost": {"metal": 6},
			"size": Vector2i.ONE,
			"production": {},
			"consumption": {},
			"storage": {"metal": 60, "food": 20, "oxygen": 20, "water": 20},
			"tags": ["engineering", "storage", "logistics"],
			"layout": "layout_05_cross",
			"description": "Expands station stockpiles for common survival and build resources.",
			"unlocked": true
		},
		"med_bay": {
			"id": "med_bay",
			"display_name": "Med Bay",
			"category": "Medical",
			"rarity": "rare",
			"cost": {"metal": 7, "data": 3, "power": 1},
			"size": Vector2i.ONE,
			"production": {},
			"consumption": {"power": 1},
			"tags": ["medical", "crew_support", "medical_support"],
			"layout": "layout_dead_south",
			"description": "Keeps recovered crew stable and supports safer cryo wake protocols.",
			"unlocked": true
		},
		"biodome": {
			"id": "biodome",
			"display_name": "Biodome",
			"category": "Bio",
			"rarity": "rare",
			"cost": {"metal": 10, "water": 4, "biomass": 4},
			"size": Vector2i.ONE,
			"production": {"food": 3, "oxygen": 2, "biomass": 2},
			"consumption": {"power": 2, "water": 1},
			"storage": {"food": 30, "oxygen": 30, "biomass": 20},
			"tags": ["bio", "food", "oxygen", "plants", "biodome"],
			"layout": "layout_02_straight",
			"description": "A larger living ecology module with stronger life-support output.",
			"unlocked": false
		},
		"xeno_lab": {
			"id": "xeno_lab",
			"display_name": "Xeno Lab",
			"category": "Anomaly",
			"rarity": "rare",
			"cost": {"metal": 8, "data": 8, "rare_minerals": 2},
			"size": Vector2i.ONE,
			"production": {"data": 3, "rare_minerals": 1},
			"consumption": {"power": 2},
			"tags": ["science", "anomaly", "xeno", "containment_risk"],
			"layout": "layout_dead_south",
			"description": "Studies alien wreckage. Valuable output, but eventually wants containment.",
			"unlocked": true
		},
		"anomaly_lab": {
			"id": "anomaly_lab",
			"display_name": "Anomaly Lab",
			"category": "Anomaly",
			"rarity": "rare",
			"cost": {"metal": 8, "data": 6, "rare_minerals": 1},
			"size": Vector2i.ONE,
			"production": {"data": 2, "rare_minerals": 1},
			"consumption": {"power": 2},
			"tags": ["science", "anomaly", "containment_risk"],
			"layout": "layout_dead_south",
			"description": "Experimental anomaly workspace. Strong research yield, strange side effects later.",
			"unlocked": true
		},
		"bio_lab": {
			"id": "bio_lab",
			"display_name": "Bio Lab",
			"category": "Bio",
			"rarity": "uncommon",
			"cost": {"metal": 6, "biomass": 3, "power": 1},
			"size": Vector2i.ONE,
			"production": {"biomass": 2, "data": 1},
			"consumption": {"power": 1, "water": 1},
			"tags": ["bio", "science", "biomass"],
			"layout": "layout_01_tee",
			"description": "Grows and studies station-compatible organic systems.",
			"unlocked": true
		},
		"command_center": {
			"id": "command_center",
			"display_name": "Command Center",
			"category": "Core",
			"rarity": "rare",
			"cost": {"metal": 10, "data": 6, "power": 2},
			"size": Vector2i.ONE,
			"production": {"data": 2},
			"consumption": {"power": 1},
			"storage": {"data": 20},
			"tags": ["core_support", "command", "data"],
			"layout": "layout_06_core",
			"description": "Auxiliary command node for BRINE's station coordination routines.",
			"unlocked": true
		},
		"corridor": {
			"id": "corridor",
			"display_name": "Corridor",
			"category": "Engineering",
			"rarity": "uncommon",
			"cost": {"metal": 2},
			"size": Vector2i.ONE,
			"production": {},
			"consumption": {},
			"tags": ["corridor", "routing"],
			"layout": "layout_02_straight",
			"description": "Cheap routing space for extending the station footprint.",
			"unlocked": true
		},
		"corner": {
			"id": "corner",
			"display_name": "Corner Corridor",
			"category": "Engineering",
			"rarity": "uncommon",
			"cost": {"metal": 2},
			"size": Vector2i.ONE,
			"production": {},
			"consumption": {},
			"tags": ["corridor", "routing"],
			"layout": "layout_04_corner",
			"description": "Turns station traffic around a corner.",
			"unlocked": true
		},
		"crew_lounge": {
			"id": "crew_lounge",
			"display_name": "Crew Lounge",
			"category": "Crew",
			"rarity": "uncommon",
			"cost": {"metal": 6, "food": 2, "oxygen": 2},
			"size": Vector2i.ONE,
			"production": {"food": 1},
			"consumption": {"oxygen": 1},
			"tags": ["crew", "morale", "hab"],
			"layout": "layout_01_tee",
			"description": "A softer place for recovered crew to gather and stabilize.",
			"unlocked": true
		},
		"holographic_core": {
			"id": "holographic_core",
			"display_name": "Holographic Core",
			"category": "Science",
			"rarity": "rare",
			"cost": {"metal": 8, "data": 8, "power": 2},
			"size": Vector2i.ONE,
			"production": {"data": 3},
			"consumption": {"power": 2},
			"storage": {"data": 25},
			"tags": ["science", "data", "core_support"],
			"layout": "layout_06_core",
			"description": "A projection lattice that helps BRINE model lost station memories.",
			"unlocked": true
		},
		"maintenance_bay": {
			"id": "maintenance_bay",
			"display_name": "Maintenance Bay",
			"category": "Engineering",
			"rarity": "common",
			"cost": {"metal": 5, "power": 1},
			"size": Vector2i.ONE,
			"production": {"integrity": 1},
			"consumption": {"power": 1},
			"tags": ["engineering", "repair"],
			"layout": "layout_01_tee",
			"description": "Repair tooling for keeping station systems patched together.",
			"unlocked": true
		},
		"med_center": {
			"id": "med_center",
			"display_name": "Med Center",
			"category": "Medical",
			"rarity": "uncommon",
			"cost": {"metal": 8, "data": 4, "power": 1},
			"size": Vector2i.ONE,
			"production": {},
			"consumption": {"power": 1},
			"tags": ["medical", "crew_support", "medical_support"],
			"layout": "layout_02_straight",
			"description": "Expanded medical support for future survivor systems.",
			"unlocked": true
		},
		"med_office": {
			"id": "med_office",
			"display_name": "Med Office",
			"category": "Medical",
			"rarity": "common",
			"cost": {"metal": 5, "data": 2},
			"size": Vector2i.ONE,
			"production": {"data": 1},
			"consumption": {"power": 1},
			"tags": ["medical", "crew_support"],
			"layout": "layout_02_straight",
			"description": "Records symptoms, failures, and recovery protocols.",
			"unlocked": true
		},
		"radio_lab": {
			"id": "radio_lab",
			"display_name": "Radio Lab",
			"category": "Science",
			"rarity": "uncommon",
			"cost": {"metal": 6, "power": 1},
			"size": Vector2i.ONE,
			"production": {"data": 2},
			"consumption": {"power": 1},
			"tags": ["science", "data", "signal"],
			"layout": "layout_03_straight_ew",
			"description": "Listens through orbital static for recoverable station signals.",
			"unlocked": true
		},
		"shield_generator": {
			"id": "shield_generator",
			"display_name": "Shield Generator",
			"category": "Security",
			"rarity": "uncommon",
			"cost": {"metal": 8, "power": 2, "rare_minerals": 1},
			"size": Vector2i.ONE,
			"production": {"integrity": 1},
			"consumption": {"power": 2},
			"tags": ["security", "shield", "engineering"],
			"layout": "layout_02_straight",
			"description": "Prototype shielding for softening future orbital hazards.",
			"unlocked": true
		}
	}

static func get_room(id: String) -> Dictionary:
	return all_rooms().get(id, {})

static func category_color(category: String) -> Color:
	return CATEGORY_COLORS.get(category, Color.WHITE)

static func get_layout(layout_id: String) -> Dictionary:
	return LAYOUTS.get(layout_id, LAYOUTS["layout_05_cross"])

static func resource_icon(resource_id: String) -> String:
	return RESOURCE_ICONS.get(resource_id, "•")
