"""Build a source-audited inventory; ledger stage text is not fresh verification."""
import json
from pathlib import Path

from audit_environment_pack import inspect_pack
from build_environment_export_contract import discover_source_ledgers, LEGACY_PACKS

ROOT = Path(__file__).resolve().parents[1]


def cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")


def build(root=ROOT):
    environment = root / "assets/environment"
    lines = ["# Environment source inventory", "",
             "Generated by `python tools/build_environment_inventory.py`. Do not edit by hand.", "",
             "Source hashes, alpha and declared runtime maps are audited before this file is written.",
             "Stage text is quoted from each source ledger; it may describe an earlier review.",
             "Follow the pack README for current evidence. This inventory does not rerun native",
             "or packaged checks and does not infer owner approval.", ""]
    source_count = identity_count = 0
    for ledger_path in discover_source_ledgers(environment):
        report = inspect_pack(ledger_path)
        recorded = {row["file"] for row in report["sources"]}
        actual = {p.relative_to(ledger_path.parent).as_posix()
                  for p in ledger_path.parent.rglob("*.png")}
        if actual != recorded:
            raise ValueError(f"Unregistered sources in {ledger_path.parent}: {actual - recorded}")
        ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
        pack = ledger_path.parent.name
        prefix = "../assets/environment/" + pack
        lines += [f"## {pack}", "",
                  f"[Evidence and integration]({prefix}/README.md) · [Source ledger]({prefix}/{ledger_path.name})",
                  "", "| Identity | Kind | Selected source | Declared ledger stage |",
                  "|---|---|---|---|"]
        for asset in ledger["assets"]:
            source = asset["selected_source"]
            lines.append(f"| {cell(asset['id'])} | {cell(asset['kind'])} | "
                         f"[{cell(source)}]({prefix}/{source}) | {cell(asset['stage'])} |")
        source_count += report["source_count"]
        identity_count += report["identity_count"]
        lines += ["", f"{report['identity_count']} selected identities / {report['source_count']} preserved source versions.", ""]
    lines += ["## Historical schemas", "",
              "These packs retain separate provenance schemas and are excluded from the totals below.",
              "Their byte checks run through the export preflight; this command does not audit them.", ""]
    for pack in sorted(LEGACY_PACKS):
        lines.append(f"- [{pack}](../assets/environment/{pack}/README.md)")
    lines += ["", f"Audited modern-ledger totals: **{identity_count} selected identities / {source_count} source versions**.", ""]
    destination = root / "docs/ENVIRONMENT_SOURCE_INVENTORY.md"
    destination.write_text("\n".join(lines), encoding="utf-8")
    print(f"Inventory written: {identity_count} identities / {source_count} sources; {destination}")


if __name__ == "__main__":
    build()
