"""Adapt the existing SceneTree fixtures into an exportable Node scene, without changing assertions."""
from pathlib import Path
import hashlib
import json

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "tests/runtime_generated"
OUT.mkdir(exist_ok=True)
base = ROOT / "tests/playtest_nursery_art.gd"
station = ROOT / "tests/playtest_production_ten_station.gd"
text = base.read_text(encoding="utf-8")
assert text.startswith("extends SceneTree")
text = text.replace("extends SceneTree", "extends Node\n# Generated by tools/build_room_export_fixture.py; edit the source fixture.\n@onready var root = get_tree().root\nvar current_scene: Node\nfunc quit(code: int = 0) -> void: get_tree().quit(code)", 1)
text = text.replace("await process_frame", "await get_tree().process_frame")
text = text.replace("current_scene = game", "get_tree().current_scene = game")
(OUT / "room_base.gd").write_text(text, encoding="utf-8")
text = station.read_text(encoding="utf-8").replace('extends "res://tests/playtest_nursery_art.gd"', 'extends "res://tests/runtime_generated/room_base.gd"', 1)
text = text.replace("await process_frame", "await get_tree().process_frame")
(OUT / "station.gd").write_text(text, encoding="utf-8")
subjects = {
    'cryo_chamber': 'cryo', 'clone_lab': 'clone', 'data_archive': 'archive',
    'biodome': 'biodome', 'xeno_lab': 'xeno', 'anomaly_lab': 'anomaly',
    'bio_lab': 'bio', 'holographic_core': 'holo',
    'med_center': 'med_center', 'med_office': 'med_office',
}
support = ROOT / 'tests/playtest_underwater_life_support.gd'
support_text = support.read_text(encoding='utf-8').replace(
    'extends "res://tests/playtest_nursery_art.gd"',
    'extends "res://tests/runtime_generated/room_base.gd"', 1)
(OUT / 'room_support.gd').write_text(support_text, encoding='utf-8')
sources = [base, station, support, ROOT / 'tests/drone_dock_checks.gd']
dispatch = ['extends Node', 'const FIXTURES = {',
            '\t"station": preload("res://tests/runtime_generated/station.gd"),']
for identity, short in subjects.items():
    source = ROOT / f'tests/playtest_{short}_room.gd'
    original = source.read_text(encoding='utf-8')
    parent = 'extends "res://tests/playtest_underwater_life_support.gd"'
    assert original.startswith(parent), source
    transformed = original.replace(parent,
        'extends "res://tests/runtime_generated/room_support.gd"', 1)
    (OUT / f'{identity}.gd').write_text(transformed, encoding='utf-8')
    dispatch.append(f'\t"{identity}": preload("res://tests/runtime_generated/{identity}.gd"),')
    sources.append(source)
for identity, filename, parent, replacement in [
    ('med_bay', 'playtest_med_bay.gd', 'playtest_underwater_life_support.gd', 'room_support.gd'),
    ('reactor', 'playtest_whole_room_station.gd', 'playtest_nursery_art.gd', 'room_base.gd'),
    ('reactor_effects', 'playtest_reactor_effects.gd', 'playtest_underwater_life_support.gd', 'room_support.gd'),
    ('reactor_lighting', 'playtest_reactor_lighting.gd', 'playtest_reactor_effects.gd', 'reactor_effects.gd'),
    ('mining_drone_bay', 'playtest_mining_drone_bay.gd', 'playtest_underwater_life_support.gd', 'room_support.gd'),
    ('salvage_drone_bay', 'playtest_salvage_drone_bay.gd', 'playtest_underwater_life_support.gd', 'room_support.gd'),
]:
    source = ROOT / 'tests' / filename
    original = source.read_text(encoding='utf-8')
    prefix = f'extends "res://tests/{parent}"'
    assert original.startswith(prefix), source
    transformed = original.replace(prefix, f'extends "res://tests/runtime_generated/{replacement}"', 1)
    (OUT / f'{identity}.gd').write_text(transformed, encoding='utf-8')
    dispatch.append(f'\t"{identity}": preload("res://tests/runtime_generated/{identity}.gd"),')
    sources.append(source)

airlock = ROOT / 'tests/test_airlock.gd'
airlock_text = airlock.read_text(encoding='utf-8')
assert airlock_text.startswith('extends SceneTree')
airlock_text = airlock_text.replace('extends SceneTree', 'extends Node\n# Generated by tools/build_room_export_fixture.py; edit the source fixture.\n@onready var root = get_tree().root\nfunc quit(code: int = 0) -> void: get_tree().quit(code)', 1)
airlock_text = airlock_text.replace('await process_frame', 'await get_tree().process_frame')
airlock_text = airlock_text.replace('current_scene=game', 'get_tree().current_scene=game')
(OUT / 'airlock.gd').write_text(airlock_text, encoding='utf-8')
dispatch.append('\t"airlock": preload("res://tests/runtime_generated/airlock.gd"),')
sources.append(airlock)

dispatch += ['}', 'func _ready() -> void:', '\tvar subject := "station"',
             '\tfor arg in OS.get_cmdline_user_args():',
             '\t\tif arg.begins_with("--room-fixture="): subject = arg.trim_prefix("--room-fixture=")',
             '\tif not FIXTURES.has(subject):',
             '\t\tpush_error("Unknown exported room fixture: " + subject)',
             '\t\tget_tree().quit(1)', '\t\treturn',
             '\tadd_child(FIXTURES[subject].new())']
(OUT / 'dispatch.gd').write_text('\n'.join(dispatch) + '\n', encoding='utf-8')
# Godot's editor/export import assigns new resource UIDs. Never synthesize UID
# strings; preserve existing pairs and validate generated pairs after import.
(OUT / "station.tscn").write_text('[gd_scene load_steps=2 format=3]\n\n[ext_resource type="Script" path="res://tests/runtime_generated/dispatch.gd" id="1"]\n\n[node name="RoomExportValidation" type="Node"]\nscript = ExtResource("1")\n')
(OUT / "sources.json").write_text(json.dumps({str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest() for p in sources}, indent=2) + "\n")
print("Generated Node bridge from unchanged assertion bodies; source hashes recorded.")
