"""Review pages for the additive room prototypes, using native captures only."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
out=R/'assets/new-room-props-2026-09-26'
rooms=json.loads((R/'rooms/new-room-expansion/definitions.json').read_text())
cards=''.join(f'''<article data-category="{r['category']}"><h2>{r['display_name']}</h2><p>{r['category']}</p><a class="shot" href="furnished-review/{r['id']}-q0.png"><img loading="lazy" data-room="{r['id']}" src="furnished-review/{r['id']}-q0.png" alt="{r['display_name']} with production Bill for scale"></a><p>{r['description']}</p></article>''' for r in rooms)
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BrineSpace · Furnished rooms</title>
<style>body{margin:0;background:#16242b;color:#dbddd4;font:16px/1.5 system-ui}header,nav,section{max-width:1400px;margin:auto;padding:24px}h1{font-size:32px;margin:4px 0}h2{font-size:20px}p{color:#abb6b4}a{color:#deb478}button,select{font:inherit;background:#283b42;color:#fff;border:1px solid #627174;padding:9px;border-radius:5px}nav{position:sticky;top:0;background:#16242bf5;z-index:1;display:flex;gap:20px;align-items:center;flex-wrap:wrap;padding-top:12px;padding-bottom:12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:20px;max-width:1400px;margin:auto;padding:24px}article{border:1px solid #34464b;border-radius:8px;padding:16px;background:#1c2e34}article img{width:100%;image-rendering:pixelated;background:#142329}article[hidden]{display:none}.runtime{width:100%;max-width:1200px}small{color:#9badad}</style>
<header><small>BRINESPACE / NATIVE ROOM REVIEW / SEPTEMBER 26</small><h1>28 furnished room prototypes</h1><p>112 layouts · 28 room cards · 75 room types in the game. Native captures include production Bill for scale. New painted risers, caps and department doors are installed. Existing owner layouts are preserved.</p><p>These rooms are available in Layout Studio and through Archived Data blueprints. Costs and outputs are provisional. This is agent-reviewed integration, awaiting your visual and gameplay review.</p><a href="../architecture-rollout-2026-09-26/index.html">Installed walls, doors and airlock motion</a> · <a href="index.html">Individual props</a> · <a href="#animation">Live-game animation captures</a></header>
<nav><label>Department <select id="department"><option value="">All departments</option>'''+''.join(f'<option>{c}</option>' for c in sorted({r['category'] for r in rooms}))+'''</select></label><label>Entrance <select id="quarter"><option value="0">South</option><option value="1">West</option><option value="2">North</option><option value="3">East</option></select></label><span id="count">28 rooms</span></nav><main class="grid">'''+cards+'''</main>
<section id="animation"><h2>Survey probe in the live renderer</h2><p>Loaded → circular amber warning → launch → scan → return → recharge. Blue status while active, red while held, yellow while charging or without power. A blocked exterior route holds the mission. Scan visibility feeds the existing exploration system; checkpoint saves preserve its phase.</p><label>Launcher wall <select id="wall"><option value="0">North</option><option value="1">East</option><option value="2">South</option><option value="3">West</option></select></label> <label>Phase <select id="phase"><option value="0000">Loaded</option><option value="0027">Warning</option><option value="0050">Launching</option><option value="0080">Cruise</option><option value="0140">Scanning</option><option value="0180">Turning</option><option value="0230">Return</option><option value="0285">Docking</option><option value="0319">Recharged</option></select></label><p><img class="runtime" id="probe" src="gameplay-review/probe-q0-t0000.png" alt="Native probe gameplay capture"></p><p>These are captured phases, not continuous video. <a href="../survey-probe-v1-2026-09-26/index.html">Open the continuous mission study</a>.</p>
<h2>Aquarium in the live renderer</h2><label>Time <select id="aquarium-time"><option value="00">0 seconds</option><option value="12">12 seconds</option><option value="24">24 seconds</option><option value="36">36 seconds</option><option value="48">48 seconds / loop join</option></select></label><p><img class="runtime" id="aquarium" src="gameplay-review/aquarium-t00.png" alt="Native aquarium gameplay capture"></p><p>Three alien swimmers, six swaying plants, two coral clusters, full sand beds and rocks. <a href="animation-studies/aquarium/aquarium-preview/">Open the continuous habitat study</a>.</p></section>
<script>const $=id=>document.getElementById(id);$('department').onchange=()=>{let n=0;document.querySelectorAll('article').forEach(a=>{a.hidden=!!$('department').value&&a.dataset.category!==$('department').value;if(!a.hidden)n++});$('count').textContent=n+' rooms'};$('quarter').onchange=()=>document.querySelectorAll('[data-room]').forEach(im=>{im.src='furnished-review/'+im.dataset.room+'-q'+$('quarter').value+'.png';im.parentElement.href=im.src});function probe(){$('probe').src='gameplay-review/probe-q'+$('wall').value+'-t'+$('phase').value+'.png'}$('wall').onchange=probe;$('phase').onchange=probe;$('aquarium-time').onchange=()=>$('aquarium').src='gameplay-review/aquarium-t'+$('aquarium-time').value+'.png';</script></html>'''
(out/'furnished.html').write_text(page,encoding='utf-8')
p=out/'index.html';s=p.read_text(encoding='utf-8')
if 'href="furnished.html"' not in s:s=s.replace('<main','<p style="padding:16px 28px"><a href="furnished.html">View the 28 furnished rooms and live-game captures →</a></p><main',1)
p.write_text(s,encoding='utf-8')
print('Built furnished gallery: 28 rooms, 112 orientations, native animation captures.')
