extends SceneTree
func _init() -> void:
 var count:=0
 for path in ["res://rooms/new-room-expansion/aquarium_view.gd", "res://rooms/new-room-expansion/art_studio_view.gd", "res://rooms/new-room-expansion/atmospheric_scrubber_view.gd", "res://rooms/new-room-expansion/bathhouse_view.gd", "res://rooms/new-room-expansion/battery_service_bay_view.gd", "res://rooms/new-room-expansion/botanical_conservatory_view.gd", "res://rooms/new-room-expansion/bulkhead_control_view.gd", "res://rooms/new-room-expansion/cargo_dispatch_view.gd", "res://rooms/new-room-expansion/crew_cinema_view.gd", "res://rooms/new-room-expansion/crew_fitness_view.gd", "res://rooms/new-room-expansion/damage_control_view.gd", "res://rooms/new-room-expansion/droid_workshop_view.gd", "res://rooms/new-room-expansion/drone_repair_depot_view.gd", "res://rooms/new-room-expansion/echo_chamber_view.gd", "res://rooms/new-room-expansion/fold_chamber_view.gd", "res://rooms/new-room-expansion/games_room_view.gd", "res://rooms/new-room-expansion/habitat_recovery_view.gd", "res://rooms/new-room-expansion/memorial_room_view.gd", "res://rooms/new-room-expansion/music_room_view.gd", "res://rooms/new-room-expansion/pressure_garden_view.gd", "res://rooms/new-room-expansion/reading_room_view.gd", "res://rooms/new-room-expansion/room_view.gd", "res://rooms/new-room-expansion/seed_vault_view.gd", "res://rooms/new-room-expansion/sensor_calibration_lab_view.gd", "res://rooms/new-room-expansion/sonar_mapping_view.gd", "res://rooms/new-room-expansion/stillwater_observatory_view.gd", "res://rooms/new-room-expansion/survey_probe_bay_view.gd", "res://rooms/new-room-expansion/tea_lounge_view.gd", "res://rooms/new-room-expansion/views.gd", "res://rooms/new-room-expansion/water_reclamation_view.gd", "res://scripts/new_room_definitions.gd", "res://scripts/aquarium_life.gd", "res://scripts/survey_probe.gd", "res://scripts/survey_probe_art.gd", "res://tools/bake_new_room_cards.gd", "res://tools/review_new_room_gameplay.gd", "res://tools/prepare_new_room_uids.gd", "res://tests/test_new_room_expansion.gd"]:
  if FileAccess.file_exists(path+".uid"):continue
  var file:=FileAccess.open(path+".uid",FileAccess.WRITE)
  file.store_string(ResourceUID.id_to_text(ResourceUID.create_id())+"\n");file.close();count+=1
 var categories:Dictionary={}
 for room in preload("res://scripts/room_database.gd").all_rooms().values():categories[room.category]=int(categories.get(room.category,0))+1
 print("UID PAIRS: ",count," added; room totals: ",categories)
 quit()
